Global:
  use_gpu: True
  epoch_num: 60
  log_smooth_window: 20
  print_batch_step: 50
  save_model_dir: output/rec/rfl/att/d1
  save_epoch_step: 1
  eval_batch_step:
    - 0
    - 1701
  cal_metric_during_train: True
  pretrained_model: 
  checkpoints:
  save_inference_dir: output/rec/rfl/att/d1/inference
  use_visualdl: False
  infer_img:
  character_dict_path: PaddleOCR/ppocr/utils/ppocr_keys_v1.txt
  character_type: ch
  max_text_length: 25
  infer_mode: False
  use_space_char: False
  save_res_path: output/rec/rfl/att/d1/predicts.txt

Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.0
  clip_norm_global: 5.0
  lr:
    name: Piecewise
    decay_epochs : [10, 20, 30]
    values : [0.001, 0.0003, 0.00009, 0.000027]

Architecture:
  model_type: rec
  algorithm: RFL
  in_channels: 1
  Transform:
    name: TPS
    num_fiducial: 20
    loc_lr: 1.0
    model_name: large
  Backbone:
    name: ResNetRFL
    use_cnt: True
    use_seq: True
  Neck:
    name: RFAdaptor
    use_v2s: True
    use_s2v: True
  Head:
    name: RFLHead  
    in_channels: 512
    hidden_size: 256
    batch_max_legnth: 25
    out_channels: 38
    use_cnt: True
    use_seq: True

Loss:
  name: RFLLoss

PostProcess:
  name: RFLLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: data/recog/image/
    label_file_list:
      - data/recog/rects.txt
    ratio_list:
      - 1.0
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - RFLLabelEncode:
      - RFLRecResizeImg:
          image_shape: [1, 32, 100]
          padding: false
          interpolation: 2
      - KeepKeys:
          keep_keys: ['image', 'label', 'length', 'cnt_label']
  loader:
    shuffle: True
    batch_size_per_card: 64
    drop_last: False
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: data/recog/image/
    label_file_list:
      - data/recog/shopsign.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - RFLLabelEncode:
      - RFLRecResizeImg:
          image_shape: [1, 32, 100]
          padding: false
          interpolation: 2
      - KeepKeys:
          keep_keys: ['image', 'label', 'length', 'cnt_label']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 64
    num_workers: 4
