Global:
  use_gpu: True
  epoch_num: 50
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: output/rec/abinet/r45/d1
  save_epoch_step: 1
  eval_batch_step:
    - 0
    - 1701
  cal_metric_during_train: False
  pretrained_model:
  checkpoints:
  save_inference_dir: output/rec/abinet/r45/d1/inference
  use_visualdl: False
  infer_img:
  character_dict_path: PaddleOCR/ppocr/utils/ppocr_keys_v1.txt
  character_type: ch
  max_text_length: 25
  infer_mode: False
  use_space_char: False
  save_res_path: output/rec/abinet/r45/d1/predicts.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.99
  clip_norm: 20.0
  lr:
    name: Piecewise
    decay_epochs: [30]
    values: [0.0001, 0.00001] 
  regularizer:
    name: 'L2'
    factor: 0.

Architecture:
  model_type: rec
  algorithm: ABINet
  in_channels: 3
  Transform:
  Backbone:
    name: ResNet45
  Head:
    name: ABINetHead
    use_lang: True
    iter_size: 3

Loss:
  name: CELoss
  ignore_index: &ignore_index 6625

PostProcess:
  name: ABINetLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: data/recog/image/
    label_file_list:
      - data/recog/rects.txt
    ratio_list:
      - 1.0
    transforms:
      - DecodeImage:
          img_mode: RGB
          channel_first: False
      - ABINetRecAug:
      - ABINetLabelEncode:
          ignore_index: *ignore_index
      - ABINetRecResizeImg:
          image_shape: [3, 32, 128]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: True
    batch_size_per_card: 64
    drop_last: False
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: data/recog/image/
    label_file_list:
      - data/recog/shopsign.txt
    transforms:
      - DecodeImage:
          img_mode: RGB
          channel_first: False
      - ABINetLabelEncode:
          ignore_index: *ignore_index
      - ABINetRecResizeImg:
          image_shape: [3, 32, 128]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 64
    num_workers: 4
    use_shared_memory: False
